[project]
authors = ["Ericsii <ericfengx@foxmail.com>"]
channels = ["nvidia", "conda-forge"]
description = "IsaacLab environment for PIXI"
name = "IsaacLab-pixi"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.10.*"

[activation.env]
ISAAC_PATH = "$PIXI_PROJECT_ROOT/.pixi/envs/default/lib/python3.10/site-packages/isaacsim"
ISAACLAB_PATH = "$PIXI_PROJECT_ROOT/IsaacLab"

[feature.gpu.system-requirements]
cuda = "11.8"
libc = { family = "glibc", version = "2.34" }

[feature.gpu.dependencies]
cuda = "==11.8"

[feature.gpu.pypi-options]
extra-index-urls = ["https://pypi.nvidia.com"]
index-strategy = "unsafe-best-match"

[feature.gpu.pypi-dependencies]
torch = { version = "==2.5.1", index = "https://download.pytorch.org/whl/cu118" }
isaacsim = { version = "==4.5.0", extras = ["all", "extscache"] }
isaaclab = { path = "IsaacLab/source/isaaclab", editable = true }
isaaclab_assets = { path = "IsaacLab/source/isaaclab_assets", editable = true }
isaaclab_tasks = { path = "IsaacLab/source/isaaclab_tasks", editable = true }
isaaclab_mimic = { path = "IsaacLab/source/isaaclab_mimic", editable = true, extras = [
  "all",
] }
isaaclab_rl = { path = "IsaacLab/source/isaaclab_rl", editable = true, extras = [
  "all",
] }

[environments]
default = { features = ["gpu"] }
